apiVersion: v1
kind: Service
metadata:
  name: {{ include "example.fullname" . }}
  labels:
    {{- include "example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePortValue }}
      nodePort: {{ .Values.service.nodePortValue }}
      {{- end }}
  selector:
    {{- include "example.selectorLabels" . | nindent 4 }}
